<%@ Page Language="VB" AutoEventWireup="false" CodeFile="frmConfigurationProcess.aspx.vb"
    Inherits="frmDepreciation_Rates" Title="Configuration Process" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <title>Configuration Process</title>
    <link id="link1" runat="server" href="StyleSheet.css" rel="Stylesheet" />
</head>

<body style="width: 800px; height: 800px">

<script src="js/Tvalidate.js" type="text/javascript"> </script>
<script type="text/javascript" language="javascript">  

 

   function Valid()
   {
   var msg;

  
   return true;
   }
   function Validate(){
  
          var msg=Valid();
          if(msg!=true)
          { 
                    if(navigator.appName=="Microsoft Internet Explorer")
                    {
                     document.getElementById("<%=msginfo.ClientID %>").innerText=msg;
                     return false;
                    }
                    else  if(navigator.appName == "Netscape")
                    {  
                     document.getElementById("<%=msginfo.ClientID %>").textContent=msg;
                     return false;
                    }   
          }
           return true;
 }
    </script>

  <form id="Form1" runat="server">
    <asp:ScriptManager ID="ScriptManager1" runat="server" EnablePageMethods="true" />

 <center>
<%--  <asp:UpdatePanel id="UpdatePanel1" runat="server"><contenttemplate>--%>
<DIV><H1 class="headingTxt">
    CONFIGURATION PROCESS</H1><CENTER><TABLE class="custTable"><TBODY><TR><TD>
    <asp:Label id="lblID" runat="server" Width="144px" Text=" ID" Visible="False"></asp:Label></TD>
    <TD><asp:TextBox id="txtID" runat="server" Visible="False" Width="144px"></asp:TextBox> </TD></TR>
    <TR><TD><asp:Label id="lblName" runat="server" Width="152px" Text="Table Name"></asp:Label></TD>
    <TD>
        <asp:DropDownList ID="cmbTableName" runat="server" Width="152px">
        </asp:DropDownList></TD></TR>
    <TR><TD style="height: 24px">
        <asp:Label ID="lblAppReq" runat="server" Text="Approval Req" Width="152px"></asp:Label></TD>
    <TD style="WIDTH: 278px; height: 24px;">
        <asp:DropDownList ID="cmbApprovalReq" runat="server" Width="152px">
            <asp:ListItem>Y</asp:ListItem>
            <asp:ListItem>N</asp:ListItem>
       
</asp:DropDownList></TD></TR>
<TR><TD>
    
<asp:Label ID="lblApprovalBy" runat="server" Text="Approval By" Width="152px"></asp:Label></TD><TD>
    <asp:DropDownList ID="cmbAppBy" runat="server" Width="64px">
         <asp:ListItem>FM</asp:ListItem>
         <asp:ListItem>RM</asp:ListItem>
         <asp:ListItem>SM</asp:ListItem>
    </asp:DropDownList>

        
</TD></TR>
<TR><TD class="btnTd" colSpan=2 style="height: 107px">
<asp:Button id="BtnSave" tabIndex=2 runat="server" Text="SAVE" CausesValidation="True" SkinID="btn" onclientclick="return Validate();" CssClass="btnStyle"></asp:Button> 
<asp:Button id="BtnDetails" tabIndex=3 runat="server" Text="DETAILS" CausesValidation="False" SkinID="btn" CssClass="btnStyle"></asp:Button> 
<%--<asp:Button id="BtnReport" tabIndex=4 runat="server" Text="REPORT" CausesValidation="False" SkinID="btn" CssClass="btnStyle"></asp:Button>--%> <!--<asp:Button id="BtnRecover" tabIndex=5 runat="server" Text="RECOVER" CausesValidation="False" SkinID="btn" __designer:wfdid="w19" CssClass="btnStyle"></asp:Button>--><BR /><asp:Label id="msginfo" runat="server" EnableTheming="True" ForeColor="Red"></asp:Label> <asp:Label id="lblmsg" runat="server" Width="240px" ForeColor="Red" meta:resourcekey="lblmsgResource1"></asp:Label></TD></TR><TR><TD style="HEIGHT: 50px" class="btnTd" colSpan=2><asp:GridView id="GridView1" runat="server" SkinID="GridView" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
<Columns>
<asp:TemplateField HeaderText="ID" Visible="False"><ItemTemplate>
<asp:Label ID="Label5" runat="server" Text='<%# Bind("ID") %>'></asp:Label>
                       
</ItemTemplate>
</asp:TemplateField>
<asp:TemplateField HeaderText="TableID" Visible="False"><ItemTemplate>
<asp:Label ID="Label1" runat="server" Text='<%# Bind("Table_ID") %>'></asp:Label>
                       
</ItemTemplate>
</asp:TemplateField>
<asp:TemplateField HeaderText="Table Name"><ItemTemplate>
<asp:Label ID="Label6" runat="server" Text='<%# Bind("TableName") %>'></asp:Label>
                       
</ItemTemplate>
</asp:TemplateField>
<asp:TemplateField HeaderText="AppReq"><ItemTemplate>
<asp:Label ID="Label2" runat="server" Text='<%# Bind("AppReq") %>'></asp:Label>
                       
</ItemTemplate>
</asp:TemplateField>

<asp:TemplateField HeaderText="AppBy"><ItemTemplate>
<asp:Label ID="Label4" runat="server" Text='<%# Bind("Appby") %>'></asp:Label>
                       
</ItemTemplate>
</asp:TemplateField>
</Columns>
</asp:GridView> 




</TD></TR></TBODY></TABLE></DIV>
</CENTER>



</form>
</body>
</html>